### PR TITLE
Arbitrary android class usage

### PR DESCRIPTION
**Pull request by code0wl**
Hi Eddy, 

I needed to change my nativescript appversion to support a different classname. The below code allows this to be used with any arbitrary android application class.

Apologies in advanced for the different formatting style.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi @code0wl, why did you close this PR? Thanks!

**Comment by code0wl** [comment]
Hi @EddyVerbruggen I was not sure if this was the direction you wanted to go with the app-version plugin. I have made a fork.

Because I needed this for a bugfix on my end. I have forked and have updated the plugin. The version I am hosting is an updated version compared to this PR. 

would you like me to re-open?

Technically just changed Android to look at 

```javascript
application.android.context.getPackageManager();
```

https://github.com/code0wl/nativescript-appversion

**Comment by EddyVerbruggen** [comment]
Thanks! I'll take a look and reopen & merge if I like it.

**Comment by EddyVerbruggen** [comment]
Reopened so I won't forget to take a look.

**Comment by code0wl** [comment]
I have updated the package.json to reflect your credentials again. Thanks!

**Comment by EddyVerbruggen** [comment]
Thanks @code0wl, I just got around to releasing it. Also added synchronous versions of the Promise-based methods this plugin already provided.

Available in 1.4.0 from npm now.

**Pull request merged**
